line-length = 79
src = ["backend/src"]
include = ["backend/src/**.py", "backend/tests/**.py"]

[lint]
extend-select = [
    "N",
    "EM",
    "G",
    "Q",
    "DTZ003",
    "INP001",
    "PIE794",
    "PIE796",
    "T201",
    "SLF001",
]

[format]
quote-style = "double"
